spring:
  application:
    name: eureka-server
    
server:
  port: 9001

eureka:
  instance:
    hostname: 127.0.0.1
  server:
    enableSelfPreservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
