server:
  port: 8091

eureka:
  client:
    serviceUrl:
      #服务注册中心地址，需按照注册中心IP进行对应修改
      defaultZone: http://127.0.0.1:9001/eureka/
      
test: this is a test message!
test01: this is a test message01!
