#当前配置服务器端口
server:
  port: 8888
spring:
  application:
    name: config-center

  cloud:
  #配置中心配置
    config:
      server:
        git:
          #配置git仓库地址
          uri: https://github.com/xcbeyond/springCloudLearning.git
          #配置仓库路径
          search-paths: config-repo
          #配置文件本地临时存储目录
#          basedir: target/config
          #访问git仓库的用户名.如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
#          username: xxx
#          password: xxx
      #配置仓库的分支
      label: master

#Eureka配置 
eureka:
  client:
    serviceUrl:
      #服务注册中心地址，需按照注册中心IP进行对应修改
      defaultZone: http://register-center:8761/eureka/
  instance:
    prefer-ip-address: true

